--SCRIPT PARA CREAR LAS TABLAS

--ZONA DE ELIMINACION DE OBJETOS

/*
DROP TABLE TRANSACCIONES;
*/

--ZONA DE CREACION DE OBJETOS

CREATE TABLE TRANSACCIONES
(
    TIPOMOV VARCHAR2(4),
    OPERACI NUMBER(1),
    NUMDOC VARCHAR2(12),
    FECHAMOV DATE,
    CENORI VARCHAR2(12),CHAR2(3),
    CODPRO NUMBER(5),
    UNICON VARCHAR2(2),
    PRECIO NUMBER(15),
    NOMPRO VARCHAR2(4000),
    CANUNI NUMBER(15),
    CANKIL NUMBER(15,3),
    AU_USUARIO VARCHAR2(10),
    AU_FECHA DATE,
    AU_HORA VARCHAR2 (10),
    OBS01 VARCHAR2(120),
    OBS02 VARCHAR2(120),
    TRANSP VARCHAR2(10),
    DOMICILIO VARCHAR2(10),
    ZONA VARCHAR2(7)
);


DELETE FROM TRANSACCIONES;