ALTER TABLE TRANSACCIONES ADD CONSTRAINT transacciones_pkey PRIMARY KEY (CODPRO);

DROP TABLE PRODUCTOSBD;

CREATE TABLE PRODUCTOSBD
(
    "CODPRO" NUMBER(5,0),
    "NOMPRO" VARCHAR2(4000 BYTE), 
    "PRECIO" NUMBER(15,0),
);

DROP TABLE PRODUCTOSBD;

INSERT INTO PRODUCTOSBD("CODPRO","PRECIO")
    SELECT CODPRO, MAX(PRECIO)
    FROM TRANSACCIONES
    GROUP BY CODPRO;
---DEBO CREAR DISPARO PARA CAPTURAR EL NOMBRE PREVIO A LA INSERCCIÓN



ALTER TABLE PRODUCTOSBD
    ADD CONSTRAINT productosbd_pkey PRIMARY KEY (CODPRO);






delete from productosbd;

